/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */

var inherits = require('inherits');

var checkType = require('checktype');



var SessionEndpoint = require('core/abstracts').SessionEndpoint;


/**
 * @classdesc
 *  Endpoint that enables Kurento to work as an HTTP server, allowing peer HTTP clients to access media.
 *
 * @abstract
 * @extends module:core/abstracts.SessionEndpoint
 *
 * @constructor module:elements/abstracts.HttpEndpoint
 *
 * @param {string} id
 */
function HttpEndpoint(id){
  SessionEndpoint.call(this, id);
};
inherits(HttpEndpoint, SessionEndpoint);


/**
 * Obtains the URL associated to this endpoint
 *
 * @param {module:elements/abstracts.HttpEndpoint~getUrlCallback} [callback]
 *
 * @return {external:Promise}
 */
HttpEndpoint.prototype.getUrl = function(callback){
  return this.invoke('getUrl', callback);
};
/**
 * @callback module:elements/abstracts.HttpEndpoint~getUrlCallback
 * @param {Error} error
 * @param {String} result
 *  The url as a String
 */


/**
 * @alias module:elements/abstracts.HttpEndpoint.constructorParams
 */
HttpEndpoint.constructorParams = {};

/**
 * @alias module:elements/abstracts.HttpEndpoint.events
 *
 * @extend module:core/abstracts.SessionEndpoint.events
 */
HttpEndpoint.events = [];
HttpEndpoint.events.concat(SessionEndpoint.events);


module.exports = HttpEndpoint;


HttpEndpoint.check = function(key, value)
{
  if(!(value instanceof HttpEndpoint))
    throw SyntaxError(key+' param should be a HttpEndpoint, not '+typeof value);
};
