/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */

var inherits = require('inherits');


/**
 * Media API for the Kurento Web SDK
 *
 * @module elements
 *
 * @copyright 2013-2014 Kurento (http://kurento.org/)
 * @license LGPL
 */

var Hub = require('core/abstracts').Hub;


/**
 * A {@link Hub} that mixes the {@link #MediaType.AUDIO} stream of its connected sources and constructs a grid with the {@link #MediaType.VIDEO} streams of its connected sources into its sink
 *
 * @class module:elements.Composite
 * @extends module:core/abstracts.Hub
 */

/**
 * Create for the given pipeline
 *
 * @constructor
 *
 * @param {string} id
 */
function Composite(id){
  Hub.call(this, id);
};
inherits(Composite, Hub);


/**
 * @type module:elements.Composite.constructorParams
 *
 * @property {MediaPipeline} mediaPipeline
 *  the {@link MediaPipeline} to which the dispatcher belongs
 */
Composite.constructorParams = {
  mediaPipeline: {
    type: 'MediaPipeline',
    required: true
  },
};

/**
 * @type module:elements.Composite.events
 *
 * @extend module:core/abstracts.Hub.events
 */
Composite.events = [];
Composite.events.concat(Hub.events);


module.exports = Composite;


Composite.check = function(key, value)
{
  if(!(value instanceof Composite))
    throw SyntaxError(key+' param should be a Composite, not '+typeof value);
};
