/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */

var inherits = require('inherits');

var checkType = require('checktype');



var Hub = require('core/abstracts').Hub;


/**
 * Create a {@link DispatcherOneToMany} belonging to the given pipeline.
 *
 * @classdesc
 *  A {@link Hub} that sends a given source to all the connected sinks
 *
 * @extends module:core/abstracts.Hub
 *
 * @constructor module:elements.DispatcherOneToMany
 *
 * @param {string} id
 */
function DispatcherOneToMany(id){
  Hub.call(this, id);
};
inherits(DispatcherOneToMany, Hub);


/**
 * Remove the source port and stop the media pipeline.
 *
 * @param {module:elements.DispatcherOneToMany~removeSourceCallback} [callback]
 *
 * @return {external:Promise}
 */
DispatcherOneToMany.prototype.removeSource = function(callback){
  return this.invoke('removeSource', callback);
};
/**
 * @callback module:elements.DispatcherOneToMany~removeSourceCallback
 * @param {Error} error
 */

/**
 * Sets the source port that will be connected to the sinks of every {@link HubPort} of the dispatcher
 *
 * @alias module:elements.DispatcherOneToMany.setSource
 *
 * @param {HubPort} source
 *  source to be broadcasted
 *
 * @param {module:elements.DispatcherOneToMany~setSourceCallback} [callback]
 *
 * @return {external:Promise}
 */
DispatcherOneToMany.prototype.setSource = function(source, callback){
  checkType('HubPort', 'source', source, {required: true});

  var params = {
    source: source,
  };

  return this.invoke('setSource', params, callback);
};
/**
 * @callback module:elements.DispatcherOneToMany~setSourceCallback
 * @param {Error} error
 */


/**
 * @alias module:elements.DispatcherOneToMany.constructorParams
 *
 * @property {MediaPipeline} mediaPipeline
 *  the {@link MediaPipeline} to which the dispatcher belongs
 */
DispatcherOneToMany.constructorParams = {
  mediaPipeline: {
    type: 'MediaPipeline',
    required: true
  },
};

/**
 * @alias module:elements.DispatcherOneToMany.events
 *
 * @extend module:core/abstracts.Hub.events
 */
DispatcherOneToMany.events = [];
DispatcherOneToMany.events.concat(Hub.events);


module.exports = DispatcherOneToMany;


DispatcherOneToMany.check = function(key, value)
{
  if(!(value instanceof DispatcherOneToMany))
    throw SyntaxError(key+' param should be a DispatcherOneToMany, not '+typeof value);
};
