/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials are made
 * available under the terms of the GNU Lesser General Public License (LGPL)
 * version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */


/**
 * Event raised when the stream that the element sends out is finished.
 *
 * @event module:elements#EndOfStream
 */

/**
 * Notify of a new gathered local candidate.
 *
 * @event module:elements#OnIceCandidate
 *
 * @type {module:elements#event:Media}
 *
 * @property {module:elements/complexTypes.IceCandidate} candidate
 *  New gathered local candidate
 */

/**
 * Notify about the change of an ICE component state.
 *
 * @event module:elements#OnIceComponentStateChanged
 *
 * @type {module:elements#event:Media}
 *
 * @property {external:Integer} streamId
 *  The ID of the stream
 * @property {external:Integer} componentId
 *  The ID of the component
 * @property {module:elements/complexTypes.IceComponentState} state
 *  The state of the component
 */

/**
 * Notify that all candidates have been gathered.
 *
 * @event module:elements#OnIceGatheringDone
 */
